version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:                                    # If you disable authentication then you need to remove username and password from connection string in appsettings.
      - MONGO_INITDB_ROOT_USERNAME=root             # set your container root username
      - MONGO_INITDB_ROOT_PASSWORD=secret           # set your container root password
    ports:
      - 27017:27017
    networks:
      - CourseLibrary
    volumes:
      - mongo:/data/db

  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - CourseLibrary
    ports:
      - 5341:80
    volumes: 
      - seq:/data

networks:
  CourseLibrary:
    name: CourseLibrary-network

volumes:
  mongo:
    driver: local
  seq:
    driver: local