@url = http://localhost:5000
@email = user1@courselibrary.io
@password = secret
@userId = ef4d6637-0efd-4cef-b61e-164a4ea0308e

###
GET {{url}}

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "user"
}

###
# @name sign_in
POST {{url}}/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}