@url = http://localhost:5000
@email = user10@courselibrary.io
@password = secret
@userId = 73a42297-6b58-4a1c-91d9-9d0e1d69c4c8

###
GET {{url}}

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "user"
}

###
# @name sign_in
POST {{url}}/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}